Update README
seqeralabs/tower-cli pull request #400
Opened 2024-04-25 10:48 UTC by llewellyn-sl

Language, link, and consistency updates for the CLI README.

2024-04-25 20:30 UTC, jason-seqera approved these changes
This is fantastic, thanks!

2024-05-07 07:58 UTC, mbosio85 requested changes
Just a minor typo at the beginning, the rest is ok for me!

2024-05-07 07:58 UTC, mbosio85 commented on README.md
> +`tw` is [Seqeta Platform](https://cloud.seqera.io/) on the command line. It brings Seqera concepts like pipelines, actions, and compute environments to the terminal.
Typo in Seqet*a

2024-05-08 14:25 UTC, llewellyn-sl commented on README.md
> +`tw` is [Seqeta Platform](https://cloud.seqera.io/) on the command line. It brings Seqera concepts like pipelines, actions, and compute environments to the terminal.
Oof thanks for catching that.

2024-05-08 14:37 UTC, mbosio85 approved these changes

2024-05-08 14:37 UTC, mbosio85 commented on README.md
>  `tw` is [Seqeta Platform](https://cloud.seqera.io/) on the command line. It brings Seqera concepts like pipelines, actions, and compute environments to the terminal.
Minor typo it's tin the first link it says Seqe**t**a instead of Seqera

2024-05-08 14:42 UTC, merged