Task 39 / List collaborators
seqeralabs/tower-cli pull request #97
Opened 2021-11-08 06:44 UTC by grananda

2021-11-08 07:16 UTC, grananda commented
@jordeu could you please the reflections? There is something wrong with it. Thanks

2021-11-08 21:39 UTC, jordeu requested changes

2021-11-08 21:39 UTC, jordeu commented on src/main/java/io/seqera/tower/cli/responses/collaborators/CollaboratorsList.java
> +        TableList table = new TableList(out, 4, "ID", "Username", "Email", "Role");
No need to add the role, because it is always `collaborator`.

2021-11-09 10:46 UTC, jordeu approved these changes

2021-11-09 10:46 UTC, merged